### PR TITLE
Deactive logs in benchmark scripts

### PR DESCRIPTION
**Pull request by frapac**
+ some minor formatting

### CODE REVIEW

**Review by sshin23 — COMMENTED** [review]
Thanks, @frapac for the improvements! I was thinking that the user may want to see the progress of running the benchmark. Now that we don't print the solver output, maybe we can at least show which problem it is currently solving?

**Comment by sshin23** [comment]
other than that, everything looks good 👍

**Comment by frapac** [comment]
Good point. I think we already have some information with: https://github.com/sshin23/MadNLP.jl/blob/master/benchmark/benchmark-power.jl#L42
But you are right: would you like me to add an option to active solver's log as well?

**Comment by sshin23** [comment]
Aha, yes you're right. And yes, I think it would be good to make it as a command line option.

**Pull request merged**
