### PR TITLE
Update NLPModels and SolverCore

### PR DESCRIPTION
**Pull request by frapac**

### CODE REVIEW

**Comment by sshin23** [comment]
Thanks for the housekeeping :+1: 

Anything else to include here?

**Comment by frapac** [comment]
Before merging this PR, I think I should ensure that the `cutest-minlp` tests are passing. Apparently, we have a problem with the `NLPModels` version...

**Comment by frapac** [comment]
Tests are finally passing :tada:

**Comment by sshin23** [comment]
@frapac Sorry for checking this late. Merging this to master.

**Pull request merged**
